libs =
import libs += libensketch-xstd%lib{ensketch-xstd}
import libs += doctest%lib{doctest-main}

exe{libensketch-xstd-tests}: {hxx ixx txx cxx}{**} $libs
{
  test = true
}

out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
