intf_libs = # Interface dependencies.

lib{ensketch-xstd}: {hxx ixx txx}{** -version} hxx{version} $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

# Export options.
#
lib{ensketch-xstd}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the ensketch/xstd/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/ensketch/xstd/
  install.subdirs = true
}
