# Library Sources
#
lib{ensketch-xstd}: {hxx ixx txx}{** -version} hxx{version}

# Version Header
#
hxx{version}: in{version} $src_root/manifest

# Include Paths
#
out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/
cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
lib{ensketch-xstd}: cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"

# Linking `pthread` Library
#
if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
  lib{ensketch-xstd}: cxx.export.libs += -pthread
}

# Installation
#
{hxx ixx txx}{*}:
{
  install         = include/ensketch/xstd/
  install.subdirs = true
}
