import libs = libensketch-xstd%lib{ensketch-xstd}

exe{basics}: {hxx ixx txx cxx}{**} $libs
# exe{basics}: cxx{main type_list value_list static_radix_tree static_identifier_list static_index_list static_zstring static_zstring_list tuple} $libs
